const data = [
  {
    id: 26569936,
    dt: '2020-12-01',
    tim: '2020-12-01 19:36:00',
    url: 'https://cn.investing.com/news/stock-market-news/article-1983582',
    auth: '英为财情',
    title: '上市三年即停产 长安汽车“甩卖”悦翔V5资产',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '财联社(北京,记者 徐昊)讯,上市仅三年即遭遇停产；在被搁置五年后，相关资产又被挂牌出售——主角正是长安汽车旗下车型悦翔V5。悦翔V5为长安旗下一款紧凑型轿车，于2012年上市，但因市场反应平平，2015年被迫停产。因“山寨”长安汽车旗下合资公司车型长安马自达3，悦翔V5在上市之初便饱受争议。数据显示，悦翔V5销量曾在上市后的第二个月达到6000余辆，其后便一蹶不振。在这次会议上，长安汽车计划将对CS35、CS75、悦翔V7这三款重点车型进行大幅度的销量上调，分别计划销售16万辆、17.4万辆和8.8万辆。在之后的几年里，CS75系列成为了长安汽车的走量车型。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.986',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26569936,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.7368420958518982,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.891',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26569936,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.7368420958518982,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.891',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: [
      {
        id: null,
        oid: 26569936,
        batch: null,
        name: '汽车',
        code: 'AC005',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        weight: 0.3400000035762787,
        kws: null,
        name: '汽车',
        nameen: 'Automobile'
      }
    ],
    prods: null,
    events: [
      {
        id: null,
        oid: 26569936,
        batch: null,
        name: '产量冻结',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '产量冻结',
        nameen: 'Production Freeze',
        code: 'AA003001',
        eventSubjects: null,
        title: null
      },
      {
        id: null,
        oid: 26569936,
        batch: null,
        name: '出售资产',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '出售资产',
        nameen: 'Asset Sale',
        code: 'AD003002012',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: [
      {
        id: 13114823,
        oid: 26569936,
        dt: null,
        tim: null,
        region: '北京市',
        region_en: 'Beijing',
        region_code: 'CSF_000000,CSF_001000,CSF_001001,CSF_CN,CSF_CN_R00001,CSF_CN_110000'
      },
      {
        id: 13114824,
        oid: 26569936,
        dt: null,
        tim: null,
        region: '重庆市',
        region_en: 'Chongqing',
        region_code: 'CSF_000000,CSF_001000,CSF_001001,CSF_CN,CSF_CN_R00006,CSF_CN_500000'
      }
    ]
  },
  {
    id: 26214160,
    dt: '2020-11-21',
    tim: '2020-11-21 09:07:00',
    url: 'http://finance.eastmoney.com/a/202011211709746118.html',
    auth: '东方财富网',
    title: '不惧利空 资金回流天齐锂业 机构游资逢高抛售长安汽车',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '不惧利空，资金回流天齐锂业 机构游资逢高抛售长安汽车本周，指数震荡上扬，两市表现坚韧，创业板指数相对较弱，进三退二。统计区间：2020年11月16日至2020年11月20日从监测到的数据上看，本周异动股数为142只，主力资金本周的买入金额为221亿元，卖出金额为223亿元，合计卖出净额为2亿元。统计区间：2020年11月16日至2020年11月20日从表二主力卖出净额前列的个股来看，本周主力总体的抛压力度也不小，共有10只个股卖出净额超过亿元，分别是长安汽车、王府井、润禾材料、奇信股份、会稽山、鲁西化工、金浦钛业、神州数码、国网英大、起步股份。长安汽车本周高位回落，机构游资集体抛售，力度十分巨大。统计区间：2020年11月16日至2020年11月20日从表三的数据可以看出，游资十分活跃，本周登榜次数超过10次的游资有18家，西藏东财拉萨系的依然是最为活跃的游资。另外，值得注意的是沪股通，沪股通主要抛售了长安汽车、鲁西化工、云铝股份、神火股份、神州数码、天音控股、美吉姆。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.923',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5925925970077515,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.716',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5925925970077515,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.716',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '002466_SZ_EQ',
        comcode: 'CSF0000001956',
        abbr: '天齐锂业',
        abbrzh: '天齐锂业',
        abbren: 'TIANQI LITHIUM',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5555555820465088,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.694',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '天齐锂业',
        nameen: 'TIANQI LITHIUM',
        orgAbbrzh: '天齐锂业',
        orgAbbren: 'Tianqi Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '000768_SZ_EQ',
        comcode: 'CSF0000002939',
        abbr: '中航飞机',
        abbrzh: '中航西飞',
        abbren: 'AVIC XAC',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.10629629343748093,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.85',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '中航飞机',
        nameen: 'AVIC Aircraft',
        orgAbbrzh: '中航西飞',
        orgAbbren: 'AVIC XAC',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '600859_SH_EQ',
        comcode: 'CSF0000002553',
        abbr: '王府井',
        abbrzh: '王府井',
        abbren: 'Wangfujing',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.09703703969717026,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.808',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '王府井',
        nameen: 'Wangfujing',
        orgAbbrzh: '王府井',
        orgAbbren: 'Wangfujing',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '00861_HK_EQ',
        comcode: 'CSF0000000238',
        abbr: '神州控股',
        abbrzh: '神州控股',
        abbren: 'DC Holdings',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08777777850627899,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.91',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '神州控股',
        nameen: 'DC Holdings',
        orgAbbrzh: '神州控股',
        orgAbbren: 'DC Holdings',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '002460_SZ_EQ',
        comcode: 'CSF0000000384',
        abbr: '赣锋锂业',
        abbrzh: '赣锋锂业',
        abbren: 'GANFENG LITHIUM',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08777777850627899,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.787',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '赣锋锂业',
        nameen: 'Ganfeng Lithium',
        orgAbbrzh: '赣锋锂业',
        orgAbbren: 'Ganfeng Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '01772_HK_EQ',
        comcode: 'CSF0000000384',
        abbr: '赣锋锂业',
        abbrzh: '赣锋锂业',
        abbren: 'Ganfeng Lithium',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08777777850627899,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.787',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '赣锋锂业',
        nameen: 'Ganfeng Lithium',
        orgAbbrzh: '赣锋锂业',
        orgAbbren: 'Ganfeng Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214160,
        batch: null,
        dt: null,
        tim: null,
        code: '000034_SZ_EQ',
        comcode: 'CSF0000001208',
        abbr: '神州数码',
        abbrzh: '神州数码',
        abbren: 'Digital China',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08777777850627899,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.91',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '神州数码',
        nameen: 'Digital China',
        orgAbbrzh: '神州数码',
        orgAbbren: 'Digital China',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26214160,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: [
      {
        id: 13012913,
        oid: 26214160,
        dt: null,
        tim: null,
        region: '上海市',
        region_en: 'Shanghai',
        region_code: 'CSF_000000,CSF_001000,CSF_001001,CSF_CN,CSF_CN_R00003,CSF_CN_310000'
      }
    ]
  },
  {
    id: 26214443,
    dt: '2020-11-21',
    tim: '2020-11-21 00:00:00',
    url: 'http://www.gushi360.com/stock/shichang/b/2020-11-21/1054071.shtml',
    auth: '股市360股票网',
    title: '[股市360]不惧利空 资金回流天齐锂业 机构游资逢高抛售长安汽车',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '----本文导读：----原标题：不惧利空，资金回流天齐锂业 机构游资逢高抛售长安汽车本周，指数震荡上扬，两市表现坚韧，创业板指数相对较弱，进三退二。统计区间：2020年11月16日至2020年11月20日从监测到的数据上看，本周异动股数为142只，主力资金本周的买入金额为221亿元，卖出金额为223亿元，合计卖出净额为2亿元。统计区间：2020年11月16日至2020年11月20日从表二主力卖出净额前列的个股来看，本周主力总体的抛压力度也不小，共有10只个股卖出净额超过亿元，分别是长安汽车、王府井、润禾材料、奇信股份、会稽山、鲁西化工、金浦钛业、神州数码、国网英大、起步股份。长安汽车本周高位回落，机构游资集体抛售，力度十分巨大。统计区间：2020年11月16日至2020年11月20日从表三的数据可以看出，游资十分活跃，本周登榜次数超过10次的游资有18家，西藏东财拉萨系的依然是最为活跃的游资。另外，值得注意的是沪股通，沪股通主要抛售了长安汽车、鲁西化工、云铝股份、神火股份、神州数码、天音控股、美吉姆。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.871',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5909090638160706,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.71',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5909090638160706,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.71',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '002466_SZ_EQ',
        comcode: 'CSF0000001956',
        abbr: '天齐锂业',
        abbrzh: '天齐锂业',
        abbren: 'TIANQI LITHIUM',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.5545454621315002,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.687',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '天齐锂业',
        nameen: 'TIANQI LITHIUM',
        orgAbbrzh: '天齐锂业',
        orgAbbren: 'Tianqi Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '000768_SZ_EQ',
        comcode: 'CSF0000002939',
        abbr: '中航飞机',
        abbrzh: '中航西飞',
        abbren: 'AVIC XAC',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.10101009905338287,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.85',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '中航飞机',
        nameen: 'AVIC Aircraft',
        orgAbbrzh: '中航西飞',
        orgAbbren: 'AVIC XAC',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '600859_SH_EQ',
        comcode: 'CSF0000002553',
        abbr: '王府井',
        abbrzh: '王府井',
        abbren: 'Wangfujing',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.0919191911816597,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.808',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '王府井',
        nameen: 'Wangfujing',
        orgAbbrzh: '王府井',
        orgAbbren: 'Wangfujing',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '00861_HK_EQ',
        comcode: 'CSF0000000238',
        abbr: '神州控股',
        abbrzh: '神州控股',
        abbren: 'DC Holdings',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08282828330993652,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.91',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '神州控股',
        nameen: 'DC Holdings',
        orgAbbrzh: '神州控股',
        orgAbbren: 'DC Holdings',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '002460_SZ_EQ',
        comcode: 'CSF0000000384',
        abbr: '赣锋锂业',
        abbrzh: '赣锋锂业',
        abbren: 'GANFENG LITHIUM',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08282828330993652,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.787',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '赣锋锂业',
        nameen: 'Ganfeng Lithium',
        orgAbbrzh: '赣锋锂业',
        orgAbbren: 'Ganfeng Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '01772_HK_EQ',
        comcode: 'CSF0000000384',
        abbr: '赣锋锂业',
        abbrzh: '赣锋锂业',
        abbren: 'Ganfeng Lithium',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08282828330993652,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.787',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '赣锋锂业',
        nameen: 'Ganfeng Lithium',
        orgAbbrzh: '赣锋锂业',
        orgAbbren: 'Ganfeng Lithium',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 26214443,
        batch: null,
        dt: null,
        tim: null,
        code: '000034_SZ_EQ',
        comcode: 'CSF0000001208',
        abbr: '神州数码',
        abbrzh: '神州数码',
        abbren: 'Digital China',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.08282828330993652,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.91',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '神州数码',
        nameen: 'Digital China',
        orgAbbrzh: '神州数码',
        orgAbbren: 'Digital China',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26214443,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: [
      {
        id: 13013004,
        oid: 26214443,
        dt: null,
        tim: null,
        region: '上海市',
        region_en: 'Shanghai',
        region_code: 'CSF_000000,CSF_001000,CSF_001001,CSF_CN,CSF_CN_R00003,CSF_CN_310000'
      }
    ]
  },
  {
    id: 26154833,
    dt: '2020-11-19',
    tim: '2020-11-19 17:48:03',
    url: 'https://www.yicai.com/news/100844739.html',
    auth: '第一财经',
    title: '股价刚创近5年新高就大跌 一机构卖出长安汽车4.3亿元',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '11月19日，长安汽车（000625）高开低走，盘中大幅下探一度触及跌停。截至收盘，该股报20.25元下跌9.3%，全日成交71.7亿元。此前的5个交易日，该股连续大涨，累计涨幅高达39%。盘后交易数据显示，深股通卖出3.98亿元并买入1.34亿元，一机构卖出4.3亿元，兴业证券陕西分公司卖出4.4亿元。除上述信息外，公司未发现近期其他公共媒体报道了可能或已经对公司股票交易价格产生较大影响的未公开重大信息。公司目前经营情况正常，内外部经营环境未发生重大变化。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.983',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26154833,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.6363636255264282,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.985',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26154833,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.6363636255264282,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.985',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26154833,
        batch: null,
        name: '股价创新高',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '股价创新高',
        nameen: 'Record High of Individual Stock Price',
        code: 'FA022',
        eventSubjects: null,
        title: null
      },
      {
        id: null,
        oid: 26154833,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 26151137,
    dt: '2020-11-19',
    tim: '2020-11-19 16:44:00',
    url: 'https://kuaixun.stcn.com/egs/202011/t20201119_2548859.html',
    auth: '证券时报网',
    title: '长安汽车跌逾9% 一机构卖出4.31亿元',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '长安汽车跌逾9% 一机构卖出4.31亿元#&#证券时报e公司讯，长安汽车(000625)今日收跌9.31%，全天成交71.7亿元。该股盘后数据显示，深股通席位卖出3.98亿元同时买入1.34亿元，一机构席位卖出4.31亿元。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.993',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26151137,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.969',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26151137,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.969',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26151137,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 26150858,
    dt: '2020-11-19',
    tim: '2020-11-19 16:36:00',
    url: 'http://finance.eastmoney.com/a/202011191707541557.html',
    auth: '东方财富网',
    title: '长安汽车一度跌停 一机构卖出4.3亿元',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '长安汽车一度跌停 一机构卖出4.3亿元摘要【数据】长安汽车今日跌9.3%，盘中一度跌停，盘后交易数据显示，深股通卖出3.98亿元并买入1.34亿元，一机构卖出4.3亿元，兴业证券陕西分公司卖出4.4亿元。（第一财经）长安汽车今日跌9.3%，盘中一度跌停，盘后交易数据显示，深股通卖出3.98亿元并买入1.34亿元，一机构卖出4.3亿元，兴业证券陕西分公司卖出4.4亿元。（文章来源：第一财经）。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.991',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26150858,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8999999761581421,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26150858,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8999999761581421,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26150858,
        batch: null,
        name: '个股下跌',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '个股下跌',
        nameen: 'Decline in Individual Stock Price',
        code: 'FA020',
        eventSubjects: null,
        title: null
      },
      {
        id: null,
        oid: 26150858,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 26150917,
    dt: '2020-11-19',
    tim: '2020-11-19 16:36:00',
    url: 'https://www.fx112.com/stock/short-1898397.html',
    auth: 'FX112财经网',
    title: '【长安汽车跌逾9% 一机构卖出4.31亿',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '【长安汽车跌逾9% 一机构卖出4.31亿#&#【长安汽车跌逾9% 一机构卖出4.31亿元】长安汽车今日收跌9.31%，全天成交71.7亿元。该股盘后数据显示，深股通席位卖出3.98亿元同时买入1.34亿元，一机构席位卖出4.31亿元。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.988',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26150917,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26150917,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26150917,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 26151578,
    dt: '2020-11-19',
    tim: '2020-11-19 00:00:00',
    url: 'http://www.gushi360.com/finance/gsxw/2020-11-19/1052958.shtml',
    auth: '股市360股票网',
    title: '[股市360]长安汽车一度跌停 一机构卖出4.3亿元',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '----本文导读：----原标题：长安汽车一度跌停 一机构卖出4.3亿元 摘要 【数据】长安汽车今日跌9.3%，盘中一度跌停，盘后交易数据显示，深股通卖出3.98亿元并买入1.34亿元，一机构卖出4.3亿元，兴业证券陕西分公司卖出4.4亿元。（第一财经）长安汽车今日跌9.3%，盘中一度跌停，盘后交易数据显示，深股通卖出3.98亿元并买入1.34亿元，一机构卖出4.3亿元，兴业证券陕西分公司卖出4.4亿元。（文章来源：第一财经） 郑重声明：东方财富网发布此信息的目的在于传播更多信息，与本站立场无关。--股市360股票频道讯。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.994',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 26151578,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.800000011920929,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 26151578,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.800000011920929,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.996',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 26151578,
        batch: null,
        name: '大盘下跌',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '大盘下跌',
        nameen: 'Broad Market Decline',
        code: 'FA012',
        eventSubjects: null,
        title: null
      },
      {
        id: null,
        oid: 26151578,
        batch: null,
        name: '机构减持',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '机构减持',
        nameen: 'Holding Reduction by Institution',
        code: 'BB002008',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 25994625,
    dt: '2020-11-16',
    tim: '2020-11-16 07:34:00',
    url: 'http://stock.jrj.com.cn/2020/11/16073431288919.shtml',
    auth: '金融界',
    title: 'A股车企三季报：8家净利润同比下滑 长安汽车、比亚迪营收净利双增',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '增速来看，长安汽车、比亚迪、江淮汽车(行情600418,诊股)及广汽集团(行情601238,诊股)前三季度营收同比增长，增速分别约23.77%、11.94%、7.7%和0.27%。图4：10家车企2020年1-9月归母净利润及同比增速营收利润综合来看，2020年前三季度营收与归母净利润均实现增长的车企有长安汽车和比亚迪。从同比变动来看，前三季度累计销量同比增长的车企有长安汽车和江淮汽车2家，增幅分别约12.01%和3.67%。图5：10家车企2020年1-9月累计销量、新能源销量及同比变动在披露新能源销量数据的车企中，除上年同期基数偏低的小康股份和*ST力帆外，其余车企前三季度累计新能源销量较2019年同期出现不同程度下滑，且降幅大于传统燃油车。长城汽车前三季度累计销售新能源汽车2.48万辆，同比下滑24.32%，同期公司燃油车累计销量同比下滑5.13%。图6: 2020年1-9月国内累计销量排名前十的新能源乘用车车型及销量同比根据乘联会公布的数据，2020年前三季度国内累计销量排名第一的新能源乘用车车型为特斯拉的Model3，累计销量约7.99万辆，约是排名第二的广汽埃安销量的2.62倍。',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.976',
    generateGraph: true,
    concepts: [
      {
        id: null,
        oid: 25994625,
        batch: null,
        conceptId: null,
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upu: null,
        upt: null,
        conceptName: '新能源汽车',
        kws: null,
        code: 'CP0031',
        name: '新能源汽车',
        nameen: 'New Energy Automobile',
        title: null
      }
    ],
    coms: [
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.612500011920929,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.881',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.612500011920929,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.881',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '002594_SZ_EQ',
        comcode: 'CSF0000002554',
        abbr: '比亚迪',
        abbrzh: '比亚迪',
        abbren: 'BYD',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.612500011920929,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.894',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '比亚迪',
        nameen: 'BYD',
        orgAbbrzh: '比亚迪',
        orgAbbren: 'BYD',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '01211_HK_EQ',
        comcode: 'CSF0000002554',
        abbr: '比亚迪股份',
        abbrzh: '比亚迪股份',
        abbren: 'BYD-H',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.612500011920929,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.894',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '比亚迪股份',
        nameen: 'BYD-H',
        orgAbbrzh: '比亚迪',
        orgAbbren: 'BYD',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '600104_SH_EQ',
        comcode: 'CSF0000000369',
        abbr: '上汽集团',
        abbrzh: '上汽集团',
        abbren: 'SAIC Motor Corporation',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.14945651590824127,
        kws: null,
        newsSentiment: '1',
        newsSentimentWeight: '0.83',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '上汽集团',
        nameen: 'SAIC Motor Corporation',
        orgAbbrzh: '上汽集团',
        orgAbbren: 'SAIC Motor Corporation',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '601777_SH_EQ',
        comcode: 'CSF0000000587',
        abbr: '*ST力帆',
        abbrzh: '*ST力帆',
        abbren: 'LIFAN IND',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.13695652782917023,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.893',
        mkt: null,
        isBond: true,
        isTech: null,
        name: '*ST力帆',
        nameen: '*ST力帆',
        orgAbbrzh: '力帆股份',
        orgAbbren: 'LIFAN IND',
        title: null,
        bond: true,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '601633_SH_EQ',
        comcode: 'CSF0000000699',
        abbr: '长城汽车',
        abbrzh: '长城汽车',
        abbren: 'GREAT WALL MOT-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.10271739214658737,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.815',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长城汽车',
        nameen: 'GREAT WALL MOT-H',
        orgAbbrzh: '长城汽车',
        orgAbbren: 'Great Wall Motor',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        dt: null,
        tim: null,
        code: '02333_HK_EQ',
        comcode: 'CSF0000000699',
        abbr: '长城汽车',
        abbrzh: '长城汽车',
        abbren: 'GREAT WALL MOT-H',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.10271739214658737,
        kws: null,
        newsSentiment: '2',
        newsSentimentWeight: '0.815',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长城汽车',
        nameen: 'GREAT WALL MOT-H',
        orgAbbrzh: '长城汽车',
        orgAbbren: 'Great Wall Motor',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: [
      {
        id: null,
        oid: 25994625,
        batch: null,
        name: '汽车',
        code: 'AC005',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        weight: 0.25,
        kws: null,
        name: '汽车',
        nameen: 'Automobile'
      }
    ],
    prods: [
      {
        id: null,
        oid: 25994625,
        batch: null,
        name: '新能源汽车',
        code: 'AC003005',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        weight: 0.11999999731779099,
        kws: null,
        name: '新能源汽车',
        nameen: 'New Energy Automobiles',
        title: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        name: '乘用车',
        code: 'AC003002',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        weight: 0.10000000149011612,
        kws: null,
        name: '乘用车',
        nameen: 'Passenger Vehicles',
        title: null
      }
    ],
    events: [
      {
        id: null,
        oid: 25994625,
        batch: null,
        name: '利润减少',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '利润减少',
        nameen: 'Profit Decline',
        code: 'CD008001',
        eventSubjects: null,
        title: null
      },
      {
        id: null,
        oid: 25994625,
        batch: null,
        name: '营收增加',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '营收增加',
        nameen: 'Revenue Growth',
        code: 'CD008032',
        eventSubjects: null,
        title: null
      }
    ],
    peoples: null,
    regions: null
  },
  {
    id: 25905708,
    dt: '2020-11-12',
    tim: '2020-11-12 16:36:36',
    url: 'http://stock.10jqka.com.cn/20201112/c624682874.shtml',
    auth: '同花顺',
    title: '长安汽车：吕来升不再担任董事',
    conzh: null,
    titleen: null,
    conen: null,
    cat: null,
    state: null,
    summary:
      '长安汽车：吕来升不再担任董事#&#长安汽车（000625）(000625.SZ)发布公告，公司董事吕来升先生因工作变动不再担任董事职务，且不在公司任职，未持有公司股票。#&#关注同花顺财经（ths518），获取更多机会',
    summaryen: null,
    batch: 2388,
    favorite: false,
    newsSentiment: '2',
    newsSentimentWeight: '0.882',
    generateGraph: true,
    concepts: null,
    coms: [
      {
        id: null,
        oid: 25905708,
        batch: null,
        dt: null,
        tim: null,
        code: '000625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安汽车',
        abbrzh: '长安汽车',
        abbren: 'CHANGAN AUTO-A',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.547',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安汽车',
        nameen: 'CHANGAN AUTO-A',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      },
      {
        id: null,
        oid: 25905708,
        batch: null,
        dt: null,
        tim: null,
        code: '200625_SZ_EQ',
        comcode: 'CSF0000001675',
        abbr: '长安B',
        abbrzh: '长安B',
        abbren: 'CHANGAN AUTO-B',
        remark: null,
        state: null,
        upt: null,
        upu: null,
        product: null,
        industry: null,
        weight: 0.8333333134651184,
        kws: null,
        newsSentiment: '0',
        newsSentimentWeight: '0.547',
        mkt: null,
        isBond: false,
        isTech: null,
        name: '长安B',
        nameen: 'CHANGAN AUTO-B',
        orgAbbrzh: '长安汽车',
        orgAbbren: 'Changan Automobile',
        title: null,
        bond: false,
        tech: null
      }
    ],
    inds: null,
    prods: null,
    events: [
      {
        id: null,
        oid: 25905708,
        batch: null,
        name: '董事辞职',
        remark: null,
        state: null,
        dt: null,
        tim: null,
        upt: null,
        upu: null,
        relNews: null,
        relAnnc: null,
        typeCode: null,
        typeName: null,
        name: '董事辞职',
        nameen: 'Director Resignation',
        code: 'CF002007',
        eventSubjects: [
          {
            eventSubjectCode: 'CSF0000001675',
            eventSubjectNamezh: '长安汽车',
            eventSubjectNameen: 'CHANGAN AUTO-A',
            eventSubjectOrgAbbrzh: '长安汽车',
            eventSubjectOrgAbbren: 'Changan Automobile',
            eventSubjectType: 1,
            eventSubjectRole: 1
          }
        ],
        title: null
      }
    ],
    peoples: null,
    regions: null
  }
]
